### ISSUE TITLE
bug: Environment variables containing `#` are cut off

### ISSUE THREAD

**Issue by tdeekens** [checkly/checkly-cli#970] opened 2024-10-22 07:45 UTC
### Node.js version

22

### NPM version

10

### @checkly/cli version

4.9.1

### Steps to reproduce

Create any check (API or Browser). This check must contain an environment variable (secret or not) such as:

```js
environmentVariables: [
 {
    key: 'FOO',
    value: 'bar#baz',
    secret: true,
 },
]
```

### What is expected?

The environment variable should be deployed under the check itself with the value `bar#baz`. When deploying it as an environment variable it's visible it's cropped off. When using a secret not directly but when entered e.g. into a password field the string is noticeable shorter.

### What is actually happening?

Said environment variable is however saved as `bar`. So essentially cropped off at the `#`.

### Any additional comments?

I've noticed the same in the Checkly UI when trying to update the environment variable. At first it appears to be saved as `bar#baz` but when saving and reloading it again is cropped at `bar`. 

This seems to correlate with the release of the [Secrets for sensitive data](https://feedback.checklyhq.com/changelog/manage-sensitive-data-in-checkly-with-secrets) release. Of course this is just a guess.

**Comment by Antoine-C** [comment] 2024-10-22 13:05
Hello @tdeekens,

Thanks for the report, I'm taking a look and will get back to you asap. Thanks!

**Comment by Antoine-C** [comment] 2024-10-22 13:15
@tdeekens I can't reproduce the issue, having an environment variable (clear, locked and/or secret) with a value as `foo#bar` doesn't cause any trouble on my end. 

Could you send me over (in our [Slack community](https://checklycommunity.slack.com/archives/D0436PV7C2Y) or by email at antoine@checklyhq.com) your `accountId` - `checkId` so I can take a look?

**Comment by sorccu** [comment] 2024-12-04 08:10
Closing as I believe this issue was resolved (or rather, could not be reproduced). Thank you for the report regardless!

**Closed by sorccu** 2024-12-04 08:10 UTC
Labels: bug
